export const siteConfig = {
  name: "Tripzy",
  shortName: "Tripzy",
  description:
    "Tripzy is Ranchi's leading self drive car rental company. Rent verified, well-maintained cars at affordable daily rates with paperless KYC, inclusive insurance, and 24/7 roadside support. Book your self drive car rental in Ranchi today.",
  url: process.env.NEXT_PUBLIC_APP_URL || "https://tripzy.in",
  ogImage: `${process.env.NEXT_PUBLIC_APP_URL || "https://tripzy.in"}/og.jpg`,
  author: "Tripzy Tours and Travels",
  keywords: [
    "self drive car rental company",
    "self drive car rental",
    "car rental near me",
    "car rental",
    "car rental ranchi",
    "ranchi",
    "car service",
    "tripzy tours",
    "tripzy",
    "tripzy car rental",
    "tripzy self drive car rental",
    "tripzy ranchi",
    "tripzy tours and travels",
    "cars",
    "rent a car ranchi",
    "self drive cars in ranchi",
    "car on rent in ranchi",
    "best car rental in ranchi",
    "car hire ranchi",
    "ranchi car rental service",
  ],
  links: {
    twitter: "https://twitter.com/tripzy",
    instagram: "https://instagram.com/tripzy",
    facebook: "https://facebook.com/tripzy",
    github: "https://github.com/tripzy100",
  },
  themeColor: {
    light: "#ffffff",
    dark: "#030712",
  },
  business: {
    name: "Tripzy Self Drive Car Rental",
    legalName: "Tripzy Tours and Travels",
    address: {
      streetAddress: "Birsa Chowk, Main Road",
      addressLocality: "Ranchi",
      addressRegion: "Jharkhand",
      postalCode: "834001",
      addressCountry: "IN",
    },
    geo: {
      latitude: 23.3441,
      longitude: 85.3096,
    },
    contactPoint: {
      telephone: "+91-9234273063",
      contactType: "customer support",
      areaServed: "IN",
      availableLanguage: ["en", "hi"],
    },
    openingHours: "Mo-Su 06:00-23:00",
    priceRange: "₹₹",
  },
};

export type SiteConfig = typeof siteConfig;
